<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */


class MasterCourseTitleForSensei {
	private $master_course_title_for_sensei_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'master_course_title_for_sensei_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'master_course_title_for_sensei_page_init' ) );
	}

	public function master_course_title_for_sensei_add_plugin_page() {
		global $mct_settings_page;
		$mct_settings_page = add_options_page(
			'Master Course Subtitle for Sensei', // page_title
			'Master Course Title for Sensei', // menu_title
			'manage_options', // capability
			'master-course-title-for-sensei', // menu_slug
			array( $this, 'master_course_title_for_sensei_create_admin_page' ) // function
		);
	}

	public function master_course_title_for_sensei_create_admin_page() {
		$this->master_course_title_for_sensei_options = get_option( 'master_course_title_for_sensei_option_name' ); ?>

		<div class="wrap">
			<h2>Master Course Title for Sensei</h2>
			<p>Plugin General Settings</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'master_course_title_for_sensei_option_group' );
					do_settings_sections( 'master-course-title-for-sensei-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function master_course_title_for_sensei_page_init() {
		register_setting(
			'master_course_title_for_sensei_option_group', // option_group
			'master_course_title_for_sensei_option_name', // option_name
			array( $this, 'master_course_title_for_sensei_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'master_course_title_for_sensei_setting_section', // id
			'Settings', // title
			array( $this, 'master_course_title_for_sensei_section_info' ), // callback
			'master-course-title-for-sensei-admin' // page
		);

		add_settings_field(
			'sentence_before_date_0', // id
			'Sentence before date:', // title
			array( $this, 'sentence_before_date_0_callback' ), // callback
			'master-course-title-for-sensei-admin', // page
			'master_course_title_for_sensei_setting_section' // section
		);

		add_settings_field(
			'date_links_to_the_last_lesson_published_1', // id
			'Date links to the last lesson published?', // title
			array( $this, 'date_links_to_the_last_lesson_published_1_callback' ), // callback
			'master-course-title-for-sensei-admin', // page
			'master_course_title_for_sensei_setting_section' // section
		);

		add_settings_field(
			'update_course_subtitle_2', // id
			'Update course subtitle: ', // title
			array( $this, 'update_course_subtitle_2_callback' ), // callback
			'master-course-title-for-sensei-admin', // page
			'master_course_title_for_sensei_setting_section' // section
		);
	}

	public function master_course_title_for_sensei_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['sentence_before_date_0'] ) ) {
			$sanitary_values['sentence_before_date_0'] = sanitize_text_field( $input['sentence_before_date_0'] );
		}

		if ( isset( $input['date_links_to_the_last_lesson_published_1'] ) ) {
			$sanitary_values['date_links_to_the_last_lesson_published_1'] = $input['date_links_to_the_last_lesson_published_1'];
		}

		if ( isset( $input['update_course_subtitle_2'] ) ) {
			$sanitary_values['update_course_subtitle_2'] = $input['update_course_subtitle_2'];
		}

		return $sanitary_values;
	}

	public function master_course_title_for_sensei_section_info() {
		
	}

	public function sentence_before_date_0_callback() {
		$date = date('d/m/Y');
		printf(
			'<div id="app"><input class="regular-text" type="text" name="master_course_title_for_sensei_option_name[sentence_before_date_0]" id="sentence_before_date_0" value="%s" placeholder="Updated on (default)" v-model="message">
				<div class="mct-example">
					<h1 class="course">Course Title</h1>
					<p>{{ default }} ' . $date . '</p>
				</div>
			</div>
			<script>new Vue({
				el: "#app",
				data: {
					message: ""
					},
				computed: {
					default: function () {
						if (this.message == "") {
							return "Udated on";
						} else {
							return this.message;
						}
					} 
				}
			})
			</script>',
			isset( $this->master_course_title_for_sensei_options['sentence_before_date_0'] ) ? esc_attr( $this->master_course_title_for_sensei_options['sentence_before_date_0']) : ''
		);
	}

	public function date_links_to_the_last_lesson_published_1_callback() {
		?> <fieldset><?php $checked = ( isset( $this->master_course_title_for_sensei_options['date_links_to_the_last_lesson_published_1'] ) && $this->master_course_title_for_sensei_options['date_links_to_the_last_lesson_published_1'] === 'always' ) ? 'checked' : '' ; ?>
		<label for="date_links_to_the_last_lesson_published_1-0"><input type="radio" name="master_course_title_for_sensei_option_name[date_links_to_the_last_lesson_published_1]" id="date_links_to_the_last_lesson_published_1-0" value="always" <?php echo $checked; ?>> Always</label><br>
		<?php $checked = ( isset( $this->master_course_title_for_sensei_options['date_links_to_the_last_lesson_published_1'] ) && $this->master_course_title_for_sensei_options['date_links_to_the_last_lesson_published_1'] === 'never' ) ? 'checked' : '' ; ?>
		<label for="date_links_to_the_last_lesson_published_1-1"><input type="radio" name="master_course_title_for_sensei_option_name[date_links_to_the_last_lesson_published_1]" id="date_links_to_the_last_lesson_published_1-1" value="never" <?php echo $checked; ?>> Never</label></fieldset> <?php
	}

	public function update_course_subtitle_2_callback() {
		?> <fieldset><?php $checked = ( isset( $this->master_course_title_for_sensei_options['update_course_subtitle_2'] ) && $this->master_course_title_for_sensei_options['update_course_subtitle_2'] === 'updated' ) ? 'checked' : '' ; ?>
		<label for="update_course_subtitle_2-0"><input type="radio" name="master_course_title_for_sensei_option_name[update_course_subtitle_2]" id="update_course_subtitle_2-0" value="updated" <?php echo $checked; ?>>  whenever a lesson is published or updated</label><br>
		<?php $checked = ( isset( $this->master_course_title_for_sensei_options['update_course_subtitle_2'] ) && $this->master_course_title_for_sensei_options['update_course_subtitle_2'] === 'published' ) ? 'checked' : '' ; ?>
		<label for="update_course_subtitle_2-1"><input type="radio" name="master_course_title_for_sensei_option_name[update_course_subtitle_2]" id="update_course_subtitle_2-1" value="published" <?php echo $checked; ?>>  only when a lesson is published initially</label></fieldset><p>*You can always define a date manually on the edit course page</p> <?php
	}

}